//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsolePLG {
	
	
	public partial class AddCompany {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.TextBox compTxtBox;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidatorPassword;
		
		protected System.Web.UI.WebControls.CheckBoxList CountriesCBList;
		
		protected System.Web.UI.WebControls.TextBox commentTxtBox;
		
		protected System.Web.UI.WebControls.Button submit;
	}
}
