//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsolePLG {
	
	
	public partial class Master {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl signMenu;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl rentalMenu;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl returnMenu;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl logMenu;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder contentPlaceHolder;
	}
}
