//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsolePLG {
	
	
	public partial class ViewByCountry {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.DropDownList countriesDropDown;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidatorCompanies;
		
		protected System.Web.UI.WebControls.DropDownList companiesDropDown;
		
		protected System.Web.UI.WebControls.Button filter;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl comments;
	}
}
